accum_iter: 1
batch_size: 4
blr: 0.001
checkpoint_path: ./log/uadfv
device: cuda
dist_on_itp: false
dist_url: env://
epochs: 60
find_unused_parameters: true
flag: train
gpus: 0,1
if_predict_label: true
if_predict_mask: true
local_rank: -1
log_dir: ./log/uadfv
log_per_epoch_count: 10
lr: 1e-4
min_lr: 1e-5
resume: ""
seed: 42
start_epoch: 0
test_batch_size: 4
num_workers: 8
pin_mem: true
record_epoch: 1
test_period: 1000


model:
  name: focal
  init_config:
    pretrained_path: "/data/disk2/yer/ForensicHub/external/FOCAL/weights/HRNet_W48_C_ssld_pretrained.pth"

no_model_eval: false


train_dataset:
  dataset_name: uadfv
  init_config:
    image_size: 512
    include_fake: true
    include_real: true
    root_dir: /data/disk2/yer/Dataset/forgery/UADFV/UADFVset
    frames_per_video: 16
    sampling: uniform          
    crop_by_landmarks: false
  name: UADFVDataset

test_dataset:
  - dataset_name: uadfv
    init_config:
      image_size: 512
      include_fake: true
      include_real: true
      root_dir: /data/disk2/yer/Dataset/forgery/UADFV/UADFVset
      frames_per_video: 16
      sampling: uniform
      crop_by_landmarks: false
    name: UADFVDataset


transform:
  init_config:
    norm_type: image_net
  name: BisaiTransform

use_amp: true
warmup_epochs: 2
weight_decay: 0.005

loss:
  seg_weight: 0.5

evaluator:
  - name: ImageF1
  - init_config:
      threshold: 0.5
    name: PixelF1
