accum_iter: 1
batch_size: 4
blr: 0.001
checkpoint_path: ./log/ffpp
device: cuda
dist_on_itp: false
dist_url: env://
epochs: 100

evaluator:
  - name: ImageF1
  - init_config:
      threshold: 0.5
    name: PixelF1

find_unused_parameters: true
flag: train
gpus: 0,1
if_predict_label: true
if_predict_mask: true
local_rank: -1
log_dir: ./log/ffpp
log_per_epoch_count: 10
lr: 1e-4
min_lr: 1e-5

# 模型配置
model:
  name: focal
  init_config:
    pretrained_path: "/data/disk2/yer/ForensicHub/external/FOCAL/weights/HRNet_W48_C_ssld_pretrained.pth"

no_model_eval: false
num_workers: 8
pin_mem: true
record_epoch: 1
test_period: 1000
resume: ""                    # 不加载 checkpoint，纯训练
seed: 42
start_epoch: 0
test_batch_size: 4

# 数据集配置（训练集）
train_dataset:
  dataset_name: ffpp
  init_config:
    image_size: 512
    include_original: true
    root_dir: /data/disk2/yer/Dataset/forgery/FF++/FFppset # 指向 FFppset 根目录
    path: /data/disk2/yer/Dataset/forgery/FF++/FFppset/annotations.csv
  name: FFPPDataset

# 数据集配置（测试集）
test_dataset:
  - dataset_name: ffpp
    init_config:
      image_size: 512
      include_original: true
      root_dir: /data/disk2/yer/Dataset/forgery/FF++/FFppset
      path: /data/disk2/yer/Dataset/forgery/FF++/FFppset/annotations.csv
    name: FFPPDataset

# 数据增强与预处理
transform:
  init_config:
    norm_type: image_net
  name: BisaiTransform

use_amp: true
warmup_epochs: 2
weight_decay: 0.005
world_size: 2

# 损失函数配置
loss:
  seg_weight: 0.5
