# focal_test_ffpp.yaml
accum_iter: 1
batch_size: 32
blr: 0.001
checkpoint_path: ./log/ffpp  #
device: cuda
dist_on_itp: false
dist_url: env://
epochs: 1
evaluator:
  - name: ImageF1
  - init_config:
      threshold: 0.5
    name: PixelF1
find_unused_parameters: true
flag: test
gpus: 0,1
if_predict_label: true
if_predict_mask: true
local_rank: -1
log_dir: ./log/ffpp
log_per_epoch_count: 20
lr: 1e-4
min_lr: 1e-5
model:
  name: focal
no_model_eval: false
num_workers: 12
pin_mem: true
record_epoch: 1
resume: "./log/ffpp/checkpoint_latest.pth"  
seed: 42
start_epoch: 0
test_batch_size: 32

test_dataset:
  - dataset_name: ffpp_test
    init_config:
      image_size: 512
      path: /data/disk2/yer/Dataset/forgery/FF++/FFppset/test.json
      root_dir: /data/disk2/yer/Dataset/forgery/FF++/FFppset
    name: FFPPDataset

transform:
  init_config:
    norm_type: image_net
  name: BisaiTransform

use_amp: true
warmup_epochs: 0
weight_decay: 0.05
world_size: 2
