accum_iter: 1
batch_size: 16
blr: 0.001
checkpoint_path: ./log/columbia
device: cuda
dist_on_itp: false
dist_url: env://
evaluator:
- name: ImageF1
- init_config:
    threshold: 0.5
  name: PixelF1
flag: test
gpus: 0,1
if_predict_label: true
if_predict_mask: true
log_dir: ./log/columbia
log_per_epoch_count: 20
lr: 1e-4
min_lr: 1e-5
model:
  init_config:
    pretrained_path: ''
  name: focal
no_model_eval: false
num_workers: 8
pin_mem: true
resume: ./log/columbia/checkpoint-68.pth
seed: 42
start_epoch: 0
test_batch_size: 16
test_dataset:
- dataset_name: columbia
  init_config:
    image_size: 512
    include_original: true
    root_dir: /data/disk2/yer/Dataset/forgery/Columbia
  name: ColumbiaDataset
transform:
  init_config:
    norm_type: image_net
  name: BisaiTransform
use_amp: true
