accum_iter: 1
batch_size: 8
blr: 0.001
checkpoint_path: ./log/columbia
device: cuda
dist_on_itp: false
dist_url: env://
epochs: 100

evaluator:
  - name: ImageF1
  - init_config:
      threshold: 0.5
    name: PixelF1

find_unused_parameters: true
flag: train
gpus: 0,1
if_predict_label: true
if_predict_mask: true
local_rank: -1
log_dir: ./log/columbia

log_per_epoch_count: 10    
lr: 1e-4
min_lr: 1e-5

model:
  name: focal
  init_config:
    pretrained_path: "/data/disk2/yer/ForensicHub/external/FOCAL/weights/HRNet_W48_C_ssld_pretrained.pth"

no_model_eval: false
num_workers: 8
pin_mem: true
record_epoch: 1
test_period: 1000
resume: ""
seed: 42
start_epoch: 0
test_batch_size: 8

train_dataset:
  dataset_name: columbia
  init_config:
    image_size: 512
    include_original: true
    root_dir: /data/disk2/yer/Dataset/forgery/Columbia
  name: ColumbiaDataset

test_dataset:
  - dataset_name: columbia
    init_config:
      image_size: 512
      include_original: true
      root_dir: /data/disk2/yer/Dataset/forgery/Columbia
    name: ColumbiaDataset

transform:
  init_config:
    norm_type: image_net
  name: BisaiTransform

use_amp: true
warmup_epochs: 2           # 热身 2 epoch，避免刚开始震荡
weight_decay: 0.005        # 降低正则，给模型更大自由度
world_size: 2

loss:
  seg_weight: 0.5
